-- 코드를 작성해주세요

WITH RECURSIVE ECOLI_STEP AS (
    SELECT ID, PARENT_ID, 1 AS DEPTH
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT ed.id, ed.parent_id, es.depth + 1 AS depth
    FROM ECOLI_DATA ed
    JOIN ECOLI_STEP es
    ON ed.parent_id = es.id
),
ECOLI_EXISTS AS (
    SELECT ed1.id
    FROM ECOLI_DATA ed1
    JOIN ECOLI_DATA ed2
    WHERE ed1.id = ed2.parent_id
    GROUP BY ed1.id
)
SELECT COUNT(DEPTH) AS COUNT, DEPTH AS GENERATION
FROM ECOLI_STEP
WHERE ID NOT IN (SELECT ID FROM ECOLI_EXISTS)
GROUP BY DEPTH
ORDER BY 2

