-- 코드를 입력하세요
WITH TOTAL_LIST AS (
SELECT
fp.product_name
,fo.product_id
,AMOUNT * PRICE AS TOTAL_PRICE
FROM FOOD_ORDER fo
JOIN FOOD_PRODUCT fp
ON fo.product_id = fp.product_id
WHERE YEAR(PRODUCE_DATE) = '2022' AND MONTH(PRODUCE_DATE) = '05'
)
SELECT
PRODUCT_ID
,PRODUCT_NAME
,SUM(TOTAL_PRICE) AS TOTAL_SALES
FROM TOTAL_LIST
GROUP BY PRODUCT_NAME
ORDER BY 3 DESC, 1















# SELECT
# f_product.PRODUCT_ID
# , f_product.PRODUCT_NAME
# , SUM(f_product.PRICE * f_order.AMOUNT) AS TOTAL_SALES
# FROM FOOD_PRODUCT f_product
# JOIN FOOD_ORDER f_order
# ON f_product.PRODUCT_ID = f_order.PRODUCT_ID
# WHERE YEAR(f_order.PRODUCE_DATE) = 2022 AND MONTH(f_order.PRODUCE_DATE) = 5
# GROUP BY PRODUCT_ID
# ORDER BY 3 DESC ,1 ASC