-- 코드를 입력하세요
WITH CAR_DIFF AS (
SELECT
c1.CAR_ID, c1.CAR_TYPE, c1.DAILY_FEE, c2.HISTORY_ID
, DATEDIFF(c2.end_date, c2.start_date) + 1 AS DIFF
FROM CAR_RENTAL_COMPANY_CAR c1
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY c2
ON c1.car_id = c2.car_id
WHERE c1.CAR_TYPE = '트럭'
)
SELECT
c4.HISTORY_ID,
CASE 
 WHEN c3.DISCOUNT_RATE IS NOT NULL
 THEN ROUND(c4.DAILY_FEE * (1 - (c3.DISCOUNT_RATE / 100)) * c4.DIFF)
 ELSE c4.DAILY_FEE * c4.DIFF
 END AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN c3
RIGHT JOIN CAR_DIFF c4
ON c3.CAR_TYPE = c4.CAR_TYPE
AND CAST(DURATION_TYPE AS DECIMAL) <= c4.DIFF
GROUP BY c4.HISTORY_ID
ORDER BY 2 DESC, 1 DESC









# SELECT
# HISTORY_ID
# , ROUND(DAILY_FEE * (100 - IFNULL(DISCOUNT_RATE, 0)) / 100 * (DATEDIFF(END_DATE, START_DATE) + 1)) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR car
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY history
# ON car.CAR_ID = history.CAR_ID AND car.CAR_TYPE = '트럭'
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN plan
# ON car.CAR_TYPE = plan.CAR_TYPE
# AND DATEDIFF(END_DATE, START_DATE) + 1 >= CAST(plan.DURATION_TYPE AS decimal)
# GROUP BY history.HISTORY_ID
# ORDER BY 2 DESC, 1 DESC