-- 코드를 입력하세요
WITH CAR AS (
SELECT
*
, COUNT(car_id) AS RECORDS
FROM 
 CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
 START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY
 CAR_ID
HAVING
 COUNT(CAR_ID) >= 5
)
SELECT
  MONTH(START_DATE) AS MONTH,
  CAR_ID,
  COUNT(CAR_ID) AS RECORDS
FROM 
  CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
  CAR_ID IN (SELECT CAR_ID FROM CAR) 
AND
  START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 
  MONTH(START_DATE), CAR_ID
ORDER BY 
  MONTH(START_DATE), CAR_ID DESC;














# SELECT
# MONTH(START_DATE) AS MONTH
# , CAR_ID
# , COUNT(CAR_ID) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE 
# CAR_ID IN (SELECT
#             CAR_ID
#           FROM
#            CAR_RENTAL_COMPANY_RENTAL_HISTORY
#           WHERE
#            START_DATE 
#            BETWEEN '2022-08-01' AND '2022-10-31'
#           GROUP BY CAR_ID
#           HAVING COUNT(CAR_ID) >= 5
#           ) 
# AND
# START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
# GROUP BY 1,2
# ORDER BY 1,2 DESC