-- 코드를 입력하세요
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE category = '인문' AND YEAR(PUBLISHED_DATE) = 2021;

# SELECT * FROM BOOK













# SELECT 
# BOOK_ID
# , date_format(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE 
# FROM BOOK
# WHERE PUBLISHED_DATE LIKE '2021%'
# AND CATEGORY = '인문'
# ORDER BY PUBLISHED_DATE ASC