-- 코드를 입력하세요
WITH MAX_CATEGORY AS (
SELECT 
CATEGORY
,MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
)
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE IN (SELECT MAX_PRICE FROM MAX_CATEGORY)
AND CATEGORY IN (SELECT CATEGORY FROM MAX_CATEGORY)
ORDER BY 2 DESC 










# SELECT
# CATEGORY
# , PRICE AS MAX_PRICE
# , PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE (PRICE, CATEGORY) IN (
# SELECT
# MAX(PRICE), CATEGORY
# FROM FOOD_PRODUCT
# GROUP BY CATEGORY
# HAVING 
# CATEGORY = '과자' 
# OR CATEGORY = '국' 
# OR CATEGORY = '김치' 
# OR CATEGORY = '식용유'
# )GROUP BY CATEGORY
# ORDER BY 2 DESC

# # SELECT * FROM FOOD_PRODUCT