-- 코드를 작성해주세요

# SELECT * FROM FISH_INFO

# SELECT 
# AVG(LENGTH)
SELECT 
COUNT(FISH_TYPE) AS FISH_COUNT
,MAX(a.LENGTH) AS MAX_LENGTH
,a.fish_type
FROM (
SELECT 
ID, FISH_TYPE, LENGTH, TIME,
CASE 
 WHEN LENGTH > 10 THEN LENGTH ELSE 10 END AS TEN
FROM FISH_INFO) a
GROUP BY a.FISH_TYPE
HAVING AVG(a.TEN) >= 33
ORDER BY 3